export const FETCH_SHIFTS_LIST = 'FETCH_SHIFTS_LIST'
export const FETCH_INVITED_CONTRACTS_LIST = 'FETCH_INVITED_CONTRACTS_LIST'
export const FILTER_SHIFTS_BY_JOB_TYPE = 'FILTER_SHIFTS_BY_JOB_TYPE'
export const FILTER_SHIFTS_BY_START_TIME = 'FILTER_SHIFTS_BY_START_TIME'

